name: QT

on:
  workflow_dispatch:
    inputs:
      name:
        description: Release version name
        required: true

run-name: ${{ github.event.inputs.name }}

jobs:
  build:
    strategy:
      matrix:
        config:
        - { name: "Windows x64 debug", os: windows-latest, arch: x64, mode: debug, qt_arch: win64_msvc2019_64, qt_archive: 'qtbase qtdeclarative' }
        # - { name: "Windows x64 releasedbg", os: windows-latest, arch: x64, mode: releasedbg, qt_arch: win64_msvc2019_64, qt_archive: 'qtbase qtdeclarative' }
        - { name: "Ubuntu x86_64 debug", os: ubuntu-latest, arch: x86_64, mode: debug, qt_arch: gcc_64, qt_archive: 'qtbase qtdeclarative icu' }
        # - { name: "Ubuntu x86_64 releasedbg", os: ubuntu-latest, arch: x86_64, mode: releasedbg, qt_arch: gcc_64, qt_archive: 'qtbase qtdeclarative icu' }
        - { name: "MacOS x86_64 debug", os: macOS-latest, arch: x86_64, mode: debug, qt_arch: clang_64, qt_archive: 'qtbase qtdeclarative qttools' }
        #- { name: "MacOS x86_64 releasedbg", os: macOS-latest, arch: x86_64, mode: releasedbg, qt_arch: clang_64, qt_archive: 'qtbase qtdeclarative qttools' }

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        target: 'desktop'
        arch: ${{ matrix.config.qt_arch }}
        cache: 'true'
        setup-python: 'false'
        archives: ${{ matrix.config.qt_archive }}

    - name: Archive and upload artifact
      shell: bash
      run: |
        tar -C ./Qt -zcvf QT-${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.mode }}.tar.gz .
        if [ "$RUNNER_OS" == "macOS" ]; then
          shasum -a 256 QT-${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.mode }}.tar.gz > SHA256SUM
        else
          sha256sum QT-${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.mode }}.tar.gz > SHA256SUM
        fi

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: QT-${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.mode }}.tar.gz
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        name: ${{ github.event.inputs.name }}
        tag_name: ${{ github.event.inputs.name }}
        append_body: true
        body_path: SHA256SUM
        repository: ZJUDMAL/XStudioPackages