name: MacOS

on:
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        arch: [x86_64]
        mode: [debug, releasedbg]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check commit tag
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        echo Commit has no tag. Add a tag!
        exit 1

    - uses: actions/checkout@v3
      with:
        repository: 'ZJUDMAL/XStudioMeshModeler'
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n
    - name: Build
      run: |
        xmake build BUILD_ALL
    
      # Setup installation configuration
    - name: Configure xmake for installation
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n

    - name: Package
      run: |
        xmake package BUILD_ALL

    - name: Archive and upload artifact
      run: |
        tar -C ./package -zcvf XStudioMeshModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz .
        shasum -a 256 XStudioMeshModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz > SHA256SUM

    - uses: actions/upload-artifact@v3
      with:
        name: XStudioMeshModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
        path: XStudioMeshModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: XStudioMeshModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        append_body: true
        body_path: SHA256SUM
        repository: ZJUDMAL/XStudioPackages