name: XStudioBrepModeler

on:
  workflow_dispatch:
    inputs:
      name:
        description: Release version name
        required: true


jobs:
  MacOS:
    strategy:
      matrix:
        os: [macOS-latest]
        arch: [x86_64]
        mode: [debug, releasedbg]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'ZJUDMAL/XStudioBrepModeler'
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n
    - name: Build
      run: |
        xmake build BUILD_ALL
    
      # Setup installation configuration
    - name: Configure xmake for installation
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n

    - name: Package
      run: |
        xmake package BUILD_ALL

    - name: Archive and upload artifact
      run: |
        tar -C ./package -zcvf XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz .
        shasum -a 256 XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz > SHA256SUM

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        name: ${{ github.event.inputs.name }}
        tag_name: ${{ github.event.inputs.name }}
        append_body: true
        body_path: SHA256SUM
        repository: ZJUDMAL/XStudioPackages

  Windows:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [debug, releasedbg]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'ZJUDMAL/XStudioBrepModeler'
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n
    - name: Build
      run: |
        xmake build BUILD_ALL
    
      # Setup installation configuration
    - name: Configure xmake for installation
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n

    - name: Package
      run: |
        xmake package BUILD_ALL

    - name: Archive and upload artifact
      run: |
        tar -C ./package -zcvf XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz .
        sha256sum XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz > SHA256SUM

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        name: ${{ github.event.inputs.name }}
        tag_name: ${{ github.event.inputs.name }}
        append_body: true
        body_path: SHA256SUM
        repository: ZJUDMAL/XStudioPackages

  Linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        mode: [debug, releasedbg]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'ZJUDMAL/XStudioBrepModeler'
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n

    - name: Build
      run: |
        xmake build BUILD_ALL
    
      # Setup installation configuration
    - name: Configure xmake for installation
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n

    - name: Package
      run: |
        xmake package BUILD_ALL

    - name: Archive and upload artifact
      run: |
        tar -C ./package -zcvf XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz .
        sha256sum XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz > SHA256SUM

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: XStudioBrepModeler-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}.tar.gz
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        token: ${{ secrets.XSTUDIOPACKAGES_PUBLISH_TOKEN }}
        name: ${{ github.event.inputs.name }}
        tag_name: ${{ github.event.inputs.name }}
        append_body: true
        body_path: SHA256SUM
        repository: ZJUDMAL/XStudioPackages